name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2', '3.3']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-ruby-${{ matrix.ruby-version }}
          path: test-results
